# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

strategy:
  matrix:
    batch1:
      minRange: 0
      maxRange: 7
    batch2:
      minRange: 8
      maxRange: 15
    batch3:
      minRange: 16
      maxRange: 23
    batch4:
      minRange: 24
      maxRange: 31
    batch5:
      minRange: 32
      maxRange: 39
    batch6:
      minRange: 40
      maxRange: 47
    batch7:
      minRange: 48
      maxRange: 55
    batch8:
      minRange: 56
      maxRange: 63
    batch9:
      minRange: 64
      maxRange: 71
    batch10:
      minRange: 72
      maxRange: 999
  maxParallel: 10

pool:
  vmImage: ubuntu-latest

schedules:
- cron: "0 */4 * * *"
  displayName: Every 4 hour build
  branches:
    include:
    - main
  always: true

steps:
- checkout: self

- script: |
    git clone "https://$(API_GITHUB_TOKEN)@github.com/migrate-bricks/automate-secret.git" ./secret
    chmod +x ./secret/automate-secret.sh
    bash ./secret/automate-secret.sh $(minRange) $(maxRange)
  displayName: 'Run Script'
  timeoutInMinutes: 360
  env:
    API_GITHUB_TOKEN: $(API_GITHUB_TOKEN)
    # JD_COOKIE: $(JD_COOKIE)
    # DDFACTORY_SHARECODES: $(DDFACTORY_SHARECODES)
    # FRUITSHARECODES: $(FRUITSHARECODES)
    # JD_JOIN_ZLC: $(JD_JOIN_ZLC)
    # JD_TRY: $(JD_TRY)
    # JD_TRY_TITLEFILTERS: $(JD_TRY_TITLEFILTERS)
    # JDHEALTH_SHARECODES: $(JDHEALTH_SHARECODES)
    # JDSGMH_SHARECODES: $(JDSGMH_SHARECODES)
    # NOTIFY_AUTOCHECKCK: $(NOTIFY_AUTOCHECKCK)
    # NOTIFY_SKIP_LIST: $(NOTIFY_SKIP_LIST)
    # PETSHARECODES: $(PETSHARECODES)
    # PLANT_BEAN_SHARECODES: $(PLANT_BEAN_SHARECODES)
    # PUSH_PLUS_TOKEN: $(PUSH_PLUS_TOKEN)
    # WP_APP_TOKEN: $(WP_APP_TOKEN)
    # WP_APP_TOKEN_ONE: $(WP_APP_TOKEN_ONE)
    # WP_TOPICIDS: $(WP_TOPICIDS)
    # JD_BEAN_SIGN_STOP_NOTIFY: $(JD_BEAN_SIGN_STOP_NOTIFY)
    # PET_NOTIFY_CONTROL: $(PET_NOTIFY_CONTROL)
    # FRUIT_NOTIFY_CONTROL: $(FRUIT_NOTIFY_CONTROL)
