
trigger:
- main
pool:
  vmImage: ubuntu-latest
schedules:
- cron: "0 */4 * * *"
  displayName: Every 4 hour build
  branches:
    include:
    - main
  always: true
jobs:
- job: batch_job
  timeoutInMinutes: 180
  cancelTimeoutInMinutes: 5
  strategy:
    matrix:
      batch1:
        index: 0
        batch: 30
      batch2:
        index: 1
        batch: 30
      batch3:
        index: 2
        batch: 30
      batch4:
        index: 3
        batch: 30
      batch5:
        index: 4
        batch: 30
      batch6:
        index: 5
        batch: 30
      batch7:
        index: 6
        batch: 30
      batch8:
        index: 7
        batch: 30
      batch9:
        index: 8
        batch: 30
      batch10:
        index: 9
        batch: 30
      batch11:
        index: 10
        batch: 30
      batch12:
        index: 11
        batch: 30
      batch13:
        index: 12
        batch: 30
      batch14:
        index: 13
        batch: 30
      batch15:
        index: 14
        batch: 30
      batch16:
        index: 15
        batch: 30
      batch17:
        index: 16
        batch: 30
      batch18:
        index: 17
        batch: 30
      batch19:
        index: 18
        batch: 30
      batch20:
        index: 19
        batch: 30
      batch21:
        index: 20
        batch: 30
      batch22:
        index: 21
        batch: 30
      batch23:
        index: 22
        batch: 30
      batch24:
        index: 23
        batch: 30
      batch25:
        index: 24
        batch: 30
      batch26:
        index: 25
        batch: 30
      batch27:
        index: 26
        batch: 30
      batch28:
        index: 27
        batch: 30
      batch29:
        index: 28
        batch: 30
      batch30:
        index: 29
        batch: 30
    maxParallel: 10
  steps:
  - checkout: self
  - script: |
      git clone "https://$(API_GITHUB_TOKEN)@github.com/migrate-bricks/automate-secret.git" ./secret
      chmod +x ./secret/automate-secret.sh
      bash ./secret/automate-secret.sh $(index) $(batch)
    displayName: 'Run Script'
    # env:
      # JD_COOKIE: $(JD_COOKIE)
      # DDFACTORY_SHARECODES: $(DDFACTORY_SHARECODES)
      # FRUITSHARECODES: $(FRUITSHARECODES)
      # JD_JOIN_ZLC: $(JD_JOIN_ZLC)
      # JD_TRY: $(JD_TRY)
      # JD_TRY_TITLEFILTERS: $(JD_TRY_TITLEFILTERS)
      # JDHEALTH_SHARECODES: $(JDHEALTH_SHARECODES)
      # JDSGMH_SHARECODES: $(JDSGMH_SHARECODES)
      # NOTIFY_AUTOCHECKCK: $(NOTIFY_AUTOCHECKCK)
      # NOTIFY_SKIP_LIST: $(NOTIFY_SKIP_LIST)
      # PETSHARECODES: $(PETSHARECODES)
      # PLANT_BEAN_SHARECODES: $(PLANT_BEAN_SHARECODES)
      # PUSH_PLUS_TOKEN: $(PUSH_PLUS_TOKEN)
      # WP_APP_TOKEN: $(WP_APP_TOKEN)
      # WP_APP_TOKEN_ONE: $(WP_APP_TOKEN_ONE)
      # WP_TOPICIDS: $(WP_TOPICIDS)
      # JD_BEAN_SIGN_STOP_NOTIFY: $(JD_BEAN_SIGN_STOP_NOTIFY)
      # PET_NOTIFY_CONTROL: $(PET_NOTIFY_CONTROL)
      # FRUIT_NOTIFY_CONTROL: $(FRUIT_NOTIFY_CONTROL)
