
trigger:
- main
pool:
  vmImage: ubuntu-latest
schedules:
- cron: "0 */4 * * *"
  displayName: scheduled build
  branches:
    include:
    - main
  always: true
jobs:
- job: update_cookie
  timeoutInMinutes: 180
  cancelTimeoutInMinutes: 5
  steps:
  - checkout: self
  - script: |
      git clone "https://oauth2:$(API_GITEE_TOKEN)@gitee.com/LinRaise/automate-secret.git" ./secret/
      python ./secret/src/jdWskey.py
    displayName: 'Update Cookie'
    env:
      API_GITEE_TOKEN: $(API_GITEE_TOKEN)
- job: execute
  dependsOn: update_cookie
  timeoutInMinutes: 180
  cancelTimeoutInMinutes: 5
  strategy:
    matrix:
      batch1:
        index: 0
        batch: 60
      batch2:
        index: 1
        batch: 60
      batch3:
        index: 2
        batch: 60
      batch4:
        index: 3
        batch: 60
      batch5:
        index: 4
        batch: 60
      batch6:
        index: 5
        batch: 60
      batch7:
        index: 6
        batch: 60
      batch8:
        index: 7
        batch: 60
      batch9:
        index: 8
        batch: 60
      batch10:
        index: 9
        batch: 60
      batch11:
        index: 10
        batch: 60
      batch12:
        index: 11
        batch: 60
      batch13:
        index: 12
        batch: 60
      batch14:
        index: 13
        batch: 60
      batch15:
        index: 14
        batch: 60
      batch16:
        index: 15
        batch: 60
      batch17:
        index: 16
        batch: 60
      batch18:
        index: 17
        batch: 60
      batch19:
        index: 18
        batch: 60
      batch20:
        index: 19
        batch: 60
      batch21:
        index: 20
        batch: 60
      batch22:
        index: 21
        batch: 60
      batch23:
        index: 22
        batch: 60
      batch24:
        index: 23
        batch: 60
      batch25:
        index: 24
        batch: 60
      batch26:
        index: 25
        batch: 60
      batch27:
        index: 26
        batch: 60
      batch28:
        index: 27
        batch: 60
      batch29:
        index: 28
        batch: 60
      batch30:
        index: 29
        batch: 60
      batch31:
        index: 30
        batch: 60
      batch32:
        index: 31
        batch: 60
      batch33:
        index: 32
        batch: 60
      batch34:
        index: 33
        batch: 60
      batch35:
        index: 34
        batch: 60
      batch36:
        index: 35
        batch: 60
      batch37:
        index: 36
        batch: 60
      batch38:
        index: 37
        batch: 60
      batch39:
        index: 38
        batch: 60
      batch40:
        index: 39
        batch: 60
      batch41:
        index: 40
        batch: 60
      batch42:
        index: 41
        batch: 60
      batch43:
        index: 42
        batch: 60
      batch44:
        index: 43
        batch: 60
      batch45:
        index: 44
        batch: 60
      batch46:
        index: 45
        batch: 60
      batch47:
        index: 46
        batch: 60
      batch48:
        index: 47
        batch: 60
      batch49:
        index: 48
        batch: 60
      batch50:
        index: 49
        batch: 60
      batch51:
        index: 50
        batch: 60
      batch52:
        index: 51
        batch: 60
      batch53:
        index: 52
        batch: 60
      batch54:
        index: 53
        batch: 60
      batch55:
        index: 54
        batch: 60
      batch56:
        index: 55
        batch: 60
      batch57:
        index: 56
        batch: 60
      batch58:
        index: 57
        batch: 60
      batch59:
        index: 58
        batch: 60
      batch60:
        index: 59
        batch: 60
    maxParallel: 10
  steps:
  - checkout: self
  - script: |
      git clone "https://oauth2:$(API_GITEE_TOKEN)@gitee.com/LinRaise/automate-secret.git" ./secret/
      chmod +x ./secret/automate-secret.sh
      bash ./secret/automate-secret.sh $(index) $(batch)
    displayName: 'Execute Script'
    env:
      API_GITEE_TOKEN: $(API_GITEE_TOKEN)
      # git clone "https://$(API_GITHUB_TOKEN)@github.com/migrate-bricks/automate-secret.git" ./secret
      # JD_COOKIE: $(JD_COOKIE)
      # DDFACTORY_SHARECODES: $(DDFACTORY_SHARECODES)
      # FRUITSHARECODES: $(FRUITSHARECODES)
      # JD_JOIN_ZLC: $(JD_JOIN_ZLC)
      # JD_TRY: $(JD_TRY)
      # JD_TRY_TITLEFILTERS: $(JD_TRY_TITLEFILTERS)
      # JDHEALTH_SHARECODES: $(JDHEALTH_SHARECODES)
      # JDSGMH_SHARECODES: $(JDSGMH_SHARECODES)
      # NOTIFY_AUTOCHECKCK: $(NOTIFY_AUTOCHECKCK)
      # NOTIFY_SKIP_LIST: $(NOTIFY_SKIP_LIST)
      # PETSHARECODES: $(PETSHARECODES)
      # PLANT_BEAN_SHARECODES: $(PLANT_BEAN_SHARECODES)
      # PUSH_PLUS_TOKEN: $(PUSH_PLUS_TOKEN)
      # WP_APP_TOKEN: $(WP_APP_TOKEN)
      # WP_APP_TOKEN_ONE: $(WP_APP_TOKEN_ONE)
      # WP_TOPICIDS: $(WP_TOPICIDS)
      # JD_BEAN_SIGN_STOP_NOTIFY: $(JD_BEAN_SIGN_STOP_NOTIFY)
      # PET_NOTIFY_CONTROL: $(PET_NOTIFY_CONTROL)
      # FRUIT_NOTIFY_CONTROL: $(FRUIT_NOTIFY_CONTROL)
