# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

strategy:
  matrix:
    batch1:
      minRange: 0
      maxRange: 24
    batch2:
      minRange: 25
      maxRange: 49
    batch3:
      minRange: 50
      maxRange: 74
    batch4:
      minRange: 75
      maxRange: 99
    batch5:
      minRange: 100
      maxRange: 124
    batch6:
      minRange: 125
      maxRange: 149
    batch7:
      minRange: 150
      maxRange: 174
    batch8:
      minRange: 175
      maxRange: 199
    batch9:
      minRange: 200
      maxRange: 224
    batch10:
      minRange: 225
      maxRange: 999
  maxParallel: 10

pool:
  vmImage: ubuntu-latest

schedules:
- cron: "0 */4 * * *"
  displayName: Every 4 hour build
  branches:
    include:
    - main
  always: true

steps:
- checkout: self

- script: |
    git clone "https://$(API_GITHUB_TOKEN)@github.com/migrate-bricks/automate-secret.git" ./secret
    chmod +x ./secret/automate-secret.sh
    bash ./secret/automate-secret.sh $(minRange) $(maxRange)
  displayName: 'Run Script'
  timeoutInMinutes: 360
  # env:
    # JD_COOKIE: $(JD_COOKIE)
    # DDFACTORY_SHARECODES: $(DDFACTORY_SHARECODES)
    # FRUITSHARECODES: $(FRUITSHARECODES)
    # JD_JOIN_ZLC: $(JD_JOIN_ZLC)
    # JD_TRY: $(JD_TRY)
    # JD_TRY_TITLEFILTERS: $(JD_TRY_TITLEFILTERS)
    # JDHEALTH_SHARECODES: $(JDHEALTH_SHARECODES)
    # JDSGMH_SHARECODES: $(JDSGMH_SHARECODES)
    # NOTIFY_AUTOCHECKCK: $(NOTIFY_AUTOCHECKCK)
    # NOTIFY_SKIP_LIST: $(NOTIFY_SKIP_LIST)
    # PETSHARECODES: $(PETSHARECODES)
    # PLANT_BEAN_SHARECODES: $(PLANT_BEAN_SHARECODES)
    # PUSH_PLUS_TOKEN: $(PUSH_PLUS_TOKEN)
    # WP_APP_TOKEN: $(WP_APP_TOKEN)
    # WP_APP_TOKEN_ONE: $(WP_APP_TOKEN_ONE)
    # WP_TOPICIDS: $(WP_TOPICIDS)
    # JD_BEAN_SIGN_STOP_NOTIFY: $(JD_BEAN_SIGN_STOP_NOTIFY)
    # PET_NOTIFY_CONTROL: $(PET_NOTIFY_CONTROL)
    # FRUIT_NOTIFY_CONTROL: $(FRUIT_NOTIFY_CONTROL)
