
trigger:
- main
pool:
  vmImage: ubuntu-latest
schedules:
- cron: "0 */4 * * *"
  displayName: scheduled build
  branches:
    include:
    - main
  always: true
jobs:
- job: renew_ptkey
  timeoutInMinutes: 180
  cancelTimeoutInMinutes: 5
  steps:
  - checkout: self
  - script: |
      git clone "https://oauth2:$(API_GITEE_TOKEN)@gitee.com/LinRaise/automate-secret.git" ./secret
      python ./secret/src/jd_wskey.py
    displayName: 'Renew Script'
    env:
      API_GITEE_TOKEN: $(API_GITEE_TOKEN)